---
- name: Destroy
  hosts:
    - localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Power off VMware VM
      community.vmware.vmware_guest:
        hostname: "{{ vmware_hostname | default(omit) }}"
        username: "{{ vmware_username | default(omit) }}"
        password: "{{ vmware_password | default(omit) }}"
        validate_certs: false
        datacenter: "{{ vmware_datacenter }}"
        name: "{{ vmware_name }}"
        state: poweredoff
      failed_when: false

    - name: Delete VMware VM
      community.vmware.vmware_guest:
        hostname: "{{ vmware_hostname | default(omit) }}"
        username: "{{ vmware_username | default(omit) }}"
        password: "{{ vmware_password | default(omit) }}"
        validate_certs: false
        datacenter: "{{ vmware_datacenter }}"
        name: "{{ vmware_name }}"
        state: absent

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

        dest: "{{ molecule_instance_config }}"
        mode: "0600"
